name: Release

on:
  push:
    # push events will publish a new image, so only trigger on main branch or semver tags.
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    # Run the workflow on pull_request events to ensure we can still build the image.
    # We only publish the image on push events (see if statements in steps below).
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa #v0.6
        with:
          version: v0.15.4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - run: |
          ko build ./cmd/caddy \
            --tags ${{ steps.meta.outputs.tags }} \
            --push ${{ github.event_name == 'push' }}
